[package]
name = "floem-things"
version = "0.1.0"
edition = "2021"

[dependencies]
floem = { git = "https://github.com/aalhitennf/floem", default-features = false }

[features]
default = ["floem/rfd-async-std"]
